# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

# REMEMBER TO ALWAYS CHANGE DIRECTORY TO CORRECT ONE TO RUN SCRIPTS
pool:
  vmImage: 'Ubuntu 16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.x'
  displayName: 'Install Node.js'
    
- script: |
    cd Khana\ POC
    npm install
  displayName: 'npm install'

- script: |
    cd Khana\ POC
    npx truffle compile
    npx truffle test --network test
  displayName: 'truffle compile & test'
  
- task: PublishTestResults@2
  condition: always()
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/truffle-test-results.xml' 
